name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "hackerhgl@gmail.com"

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          mv out/* .
          rm -rf out
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force